name: Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Bump version and create release
        id: release
        run: |
          # Extract commit message from the latest commit
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")

          # Extract current version
          CURRENT_VERSION=$(npm version --json | jq -r .version)

          # Use semantic-release to determine the next version
          npx semantic-release --dry-run

          # Extract the next version from the release dry-run output
          NEXT_VERSION=$(grep 'The next release version is' ./.releaserc | awk '{print $NF}')

          # Set the new version
          npm version "$NEXT_VERSION"

          # Create a GitHub release with the commit message as release notes
          gh release create "$NEXT_VERSION" -t "$NEXT_VERSION" -n "$COMMIT_MESSAGE"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

