name: Upload File to Release

on:
  release:
    types:
      - published

jobs:
  upload-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Upload File to Release
      uses: actions/upload-release-asset@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        asset_name: esp8266-switch.bin
        asset_path: ./build/esp8266.esp8266.esp8285/esp8266-switch.ino.bin
        upload_url: ${{ github.event.release.upload_url }}
        asset_content_type: application/octet-stream
