name: Upload File to Release

on:
  release:
    types:
      - published

jobs:
  upload-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug
      run: |
          echo "RELEASE_TOKEN:${{ secrets.RELEASE_TOKEN }}"
          env

    - name: Upload File to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/esp8266.esp8266.esp8285/esp8266-switch.ino.bin
        asset_name: esp8266-switch.bin
        asset_content_type: application/octet-stream

